name: resume-build

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: make install

    - name: Build site
      run: make build

    - name: Convert resume to pdf
      run: sudo apt-get install -y wkhtmltopdf && make pdf

    - name: Release resume
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: false
        title: Release v${{ github.run_number }}
        files: ./theme/assets/ozcanyarimdunya.pdf

    - name: Publish site to the GitHub pages
      run: make publish
