name: Deploy resume

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: make install
      - name: Build mkdocs
        run: make build
      - name: Convert resume to pdf with pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=./theme/assets/resume-pandoc.pdf site/index.html
      - name: Publish to GitHub pages
        run: make publish
