name: Deploy resume

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: make install
      - name: Build mkdocs
        run: make build
      - name: Convert resume to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./site/index.html
          outputFile: ./site/resume.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - name: Publish to GitHub pages
        run: ls -la && make publish
